from __future__ import annotations

import shutil
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import fitz  # PyMuPDF

from app.core.config import Settings, get_settings
from app.services.storage import JsonStore
from app.utils.text import (
    clean_title,
    extract_equations_from_text,
    extract_examples_from_text,
    extract_figures_from_page,
    is_probable_upper_heading,
    normalize_text,
    parse_section_heading,
    split_paragraphs,
)


@dataclass
class SectionCandidate:
    section_id: str
    title: str
    level: int
    page_start: int
    page_end: int
    parent_section_id: str | None = None
    section_type: str = "official"
    start_heading: str | None = None
    end_heading: str | None = None


class PDFIngestor:
    """Offline ingestion pipeline for a textbook PDF.

    The output is a book folder under data/books/{book_id}, containing:
    - original.pdf
    - book_meta.json
    - toc.json
    - section_map.json
    - section_packs/*.json
    - page_text.json
    - figure_map.json
    """

    def __init__(self, settings: Settings | None = None):
        self.settings = settings or get_settings()
        self.store = JsonStore(self.settings)

    def ingest(
        self,
        *,
        book_id: str,
        pdf_path: str | Path,
        title: str | None = None,
        author: str | None = None,
        overwrite: bool = False,
        aliases: dict[str, str] | None = None,
    ) -> dict[str, Any]:
        source = Path(pdf_path).expanduser().resolve()
        if not source.exists():
            raise FileNotFoundError(str(source))

        book_dir = self.store.book_dir(book_id)
        if book_dir.exists() and overwrite:
            shutil.rmtree(book_dir)
        book_dir.mkdir(parents=True, exist_ok=True)
        (book_dir / "section_packs").mkdir(exist_ok=True)

        target_pdf = book_dir / "original.pdf"
        if source != target_pdf:
            shutil.copy2(source, target_pdf)

        warnings: list[str] = []
        doc = fitz.open(target_pdf)
        try:
            page_count = doc.page_count
            page_records = self._extract_pages(doc)
            official_sections = self._extract_official_sections(doc, page_count)
            if not official_sections:
                warnings.append("No PDF outline or numbered headings were detected. Search still works by pages.")
            derived_sections = self._derive_subsections(official_sections, page_records)
            all_sections = official_sections + derived_sections
            figure_map = self._build_figure_map(page_records, all_sections)
            section_map = self._build_section_map(all_sections)
            toc = self._build_toc(official_sections, derived_sections)

            if aliases:
                self.store.save_json(book_id, "section_aliases.json", aliases)
            elif not (book_dir / "section_aliases.json").exists():
                self.store.save_json(book_id, "section_aliases.json", {})

            created = datetime.now(UTC).isoformat()
            meta = {
                "book_id": book_id,
                "title": title or self._guess_title(doc, source),
                "author": author,
                "source_file": source.name,
                "page_count": page_count,
                "created_at": created,
                "updated_at": created,
                "version": "1",
                "notes": "Generated by Teaching GPT Backend PDFIngestor.",
            }

            self.store.save_json(book_id, "book_meta.json", meta)
            self.store.save_json(book_id, "page_text.json", {"pages": page_records})
            self.store.save_json(book_id, "section_map.json", section_map)
            self.store.save_json(book_id, "toc.json", toc)
            self.store.save_json(book_id, "figure_map.json", figure_map)

            self._write_section_packs(book_id, all_sections, section_map, page_records, figure_map)

            return {
                "book_id": book_id,
                "title": meta["title"],
                "page_count": page_count,
                "official_sections": len(official_sections),
                "derived_sections": len(derived_sections),
                "figures": len(figure_map),
                "data_path": str(book_dir),
                "warnings": warnings,
            }
        finally:
            doc.close()

    def _extract_pages(self, doc: fitz.Document) -> list[dict[str, Any]]:
        pages: list[dict[str, Any]] = []
        for page_index in range(doc.page_count):
            page = doc.load_page(page_index)
            text = normalize_text(page.get_text("text"))
            pages.append(
                {
                    "page_index": page_index,
                    "page_number": page_index + 1,
                    "text": text,
                }
            )
        return pages

    def _extract_official_sections(self, doc: fitz.Document, page_count: int) -> list[SectionCandidate]:
        sections: list[SectionCandidate] = []
        toc = doc.get_toc(simple=True)
        for item in toc:
            if len(item) < 3:
                continue
            level, raw_title, page_number = item[0], item[1], item[2]
            parsed = parse_section_heading(raw_title)
            if parsed:
                section_id, title = parsed
            else:
                # Some PDF outlines omit the section number. Keep chapter-like titles only if they begin with a digit.
                continue
            start = max(1, int(page_number))
            sections.append(
                SectionCandidate(
                    section_id=section_id,
                    title=title,
                    level=int(level),
                    page_start=start,
                    page_end=page_count,
                    section_type="official",
                )
            )

        # Many textbooks have PDF outlines only at chapter level. Always scan pages for
        # numbered headings as well, then merge with the outline-derived candidates.
        scan_start_page = min((s.page_start for s in sections), default=1)
        scanned_sections = self._scan_numbered_headings_from_pages(doc, page_count, min_page=scan_start_page)
        by_id: dict[str, SectionCandidate] = {s.section_id: s for s in sections}
        for scanned in scanned_sections:
            existing = by_id.get(scanned.section_id)
            if existing is None:
                by_id[scanned.section_id] = scanned
            else:
                # Prefer the more precise page-scan title when the outline title is empty/noisy.
                if len(scanned.title) > len(existing.title) and scanned.page_start >= existing.page_start:
                    existing.title = scanned.title
        sections = list(by_id.values())

        sections.sort(key=lambda s: (s.page_start, self._section_sort_key(s.section_id)))
        for idx, section in enumerate(sections):
            next_start = sections[idx + 1].page_start if idx + 1 < len(sections) else page_count + 1
            section.page_end = max(section.page_start, min(page_count, next_start - 1))
            section.parent_section_id = self._parent_id(section.section_id)
        return sections

    def _scan_numbered_headings_from_pages(
        self,
        doc: fitz.Document,
        page_count: int,
        *,
        min_page: int = 1,
    ) -> list[SectionCandidate]:
        sections: list[SectionCandidate] = []
        seen: set[str] = set()
        start_index = max(0, min_page - 1)
        for page_index in range(start_index, page_count):
            text = normalize_text(doc.load_page(page_index).get_text("text"))
            for raw_line in text.splitlines():
                line = raw_line.strip()
                parsed = parse_section_heading(line)
                if not parsed:
                    continue
                sid, title = parsed
                title = self._clean_scanned_heading_title(title)
                if sid in seen:
                    continue
                if not self._is_valid_scanned_heading(sid, title):
                    continue
                seen.add(sid)
                sections.append(
                    SectionCandidate(
                        section_id=sid,
                        title=title,
                        level=sid.count(".") + 1,
                        page_start=page_index + 1,
                        page_end=page_count,
                        section_type="official",
                    )
                )
        return sections

    @staticmethod
    def _clean_scanned_heading_title(title: str) -> str:
        # TOC-like scanned lines often end with a page number; real page headings usually do not.
        # Removing it is harmless for titles like "The Origins ... 19".
        import re

        title = clean_title(title)
        return re.sub(r"\s+\d{1,4}$", "", title).strip()

    @staticmethod
    def _is_valid_scanned_heading(section_id: str, title: str) -> bool:
        import re

        parts = section_id.split(".")
        if len(parts) > 4:
            return False
        try:
            first = int(parts[0])
        except ValueError:
            return False
        if first <= 0 or first > 50:
            return False
        lowered = title.lower()
        if not title or lowered.startswith("chapter"):
            return False
        letters = [c for c in title if c.isalpha()]
        if len(letters) < 5:
            return False
        if title[0].islower():
            return False
        # For subsection headings found inside pages, require heading-like capitalization.
        # This filters preview sentences such as "2.2 discusses light...".
        if len(parts) >= 2:
            upper_ratio = sum(1 for c in letters if c.isupper()) / len(letters)
            title_case_words = sum(1 for w in re.findall(r"[A-Za-z]+", title) if w[:1].isupper())
            word_count = max(1, len(re.findall(r"[A-Za-z]+", title)))
            if upper_ratio < 0.45 and title_case_words / word_count < 0.65:
                return False
        return True

    def _derive_subsections(
        self,
        official_sections: list[SectionCandidate],
        page_records: list[dict[str, Any]],
    ) -> list[SectionCandidate]:
        derived: list[SectionCandidate] = []
        official_ids = {s.section_id for s in official_sections}
        for section in official_sections:
            # Derive only under regular numbered sections, not whole chapters.
            if section.section_id.count(".") < 1:
                continue
            records = page_records[section.page_start - 1 : section.page_end]
            headings: list[tuple[str, int]] = []
            for record in records:
                for line in record.get("text", "").splitlines():
                    line = clean_title(line)
                    if is_probable_upper_heading(line):
                        # Avoid duplicate page headers.
                        if line.upper() == section.title.upper():
                            continue
                        if headings and headings[-1][0].upper() == line.upper():
                            continue
                        headings.append((line.title(), int(record["page_number"])))
            if not headings:
                continue
            for idx, (heading, page_number) in enumerate(headings, start=1):
                sid = f"{section.section_id}.{idx}"
                if sid in official_ids:
                    continue
                end_page = headings[idx][1] if idx < len(headings) else section.page_end
                if idx < len(headings):
                    end_page = max(page_number, end_page - 1)
                derived.append(
                    SectionCandidate(
                        section_id=sid,
                        title=heading,
                        level=section.level + 1,
                        page_start=page_number,
                        page_end=end_page,
                        parent_section_id=section.section_id,
                        section_type="derived",
                        start_heading=heading,
                        end_heading=headings[idx][0] if idx < len(headings) else None,
                    )
                )
        return derived

    def _build_figure_map(
        self,
        page_records: list[dict[str, Any]],
        sections: list[SectionCandidate],
    ) -> dict[str, Any]:
        figure_map: dict[str, Any] = {}
        for record in page_records:
            page_number = int(record["page_number"])
            for fig in extract_figures_from_page(record.get("text", "")):
                fig_id = fig["figure_id"]
                related = [s.section_id for s in sections if s.page_start <= page_number <= s.page_end]
                figure_map[fig_id] = {
                    "figure_id": fig_id,
                    "label": fig.get("label") or f"Fig {fig_id}",
                    "caption": fig.get("caption"),
                    "page_index": page_number - 1,
                    "page_number": page_number,
                    "context": self._page_context_around(record.get("text", ""), f"FIGURE {fig_id}"),
                    "related_section_ids": related,
                }
        return figure_map

    def _build_section_map(self, sections: list[SectionCandidate]) -> dict[str, Any]:
        ordered = sorted(sections, key=lambda s: (s.page_start, self._section_sort_key(s.section_id)))
        ids = [s.section_id for s in ordered]
        mapping: dict[str, Any] = {}
        for idx, s in enumerate(ordered):
            mapping[s.section_id] = {
                "book_id": None,
                "section_id": s.section_id,
                "parent_section_id": s.parent_section_id,
                "title": s.title,
                "level": s.level,
                "page_start": s.page_start,
                "page_end": s.page_end,
                "section_type": s.section_type,
                "start_heading": s.start_heading,
                "end_heading": s.end_heading,
                "previous_sections": ids[max(0, idx - 3) : idx],
                "next_sections": ids[idx + 1 : idx + 4],
                "prerequisites": ids[max(0, idx - 3) : idx],
            }
        return mapping

    def _build_toc(
        self,
        official_sections: list[SectionCandidate],
        derived_sections: list[SectionCandidate],
    ) -> dict[str, Any]:
        all_items = official_sections + derived_sections
        return {
            "items": [
                {
                    "section_id": s.section_id,
                    "title": s.title,
                    "level": s.level,
                    "page_start": s.page_start,
                    "page_end": s.page_end,
                    "parent_section_id": s.parent_section_id,
                    "section_type": s.section_type,
                }
                for s in sorted(all_items, key=lambda x: (x.page_start, self._section_sort_key(x.section_id)))
            ]
        }

    def _write_section_packs(
        self,
        book_id: str,
        sections: list[SectionCandidate],
        section_map: dict[str, Any],
        page_records: list[dict[str, Any]],
        figure_map: dict[str, Any],
    ) -> None:
        for section in sections:
            section_text = self._section_text(section, page_records)
            paragraphs = split_paragraphs(section_text)
            source_pages = []
            for page_number in range(section.page_start, section.page_end + 1):
                source_pages.append(
                    {
                        "page_index": page_number - 1,
                        "page_number": page_number,
                    }
                )
            figures = [
                fig
                for fig in figure_map.values()
                if fig.get("page_number") and section.page_start <= int(fig["page_number"]) <= section.page_end
            ]
            equations = []
            examples = []
            for page_number in range(section.page_start, section.page_end + 1):
                page_text = page_records[page_number - 1].get("text", "")
                equations.extend(extract_equations_from_text(page_text, page_number=page_number))
                examples.extend(extract_examples_from_text(page_text, page_number=page_number))
            equations = self._dedupe_by_key(equations, "equation_id")
            examples = self._dedupe_by_key(examples, "example_id")
            pack = {
                "book_id": book_id,
                "section_id": section.section_id,
                "resolved_section_id": section.section_id,
                "parent_section_id": section.parent_section_id,
                "title": section.title,
                "page_start": section.page_start,
                "page_end": section.page_end,
                "section_type": section.section_type,
                "summary": self._make_naive_summary(section.title, paragraphs),
                "text_blocks": [
                    {
                        "type": "heading" if idx == 0 and paragraph.lower() == section.title.lower() else "paragraph",
                        "text": paragraph,
                        "page_number": None,
                    }
                    for idx, paragraph in enumerate(paragraphs)
                ],
                "figures": figures,
                "equations": equations,
                "examples": examples,
                "source_pages": source_pages,
                "previous_sections": section_map[section.section_id]["previous_sections"],
                "next_sections": section_map[section.section_id]["next_sections"],
                "prerequisites": section_map[section.section_id]["prerequisites"],
                "warnings": [],
            }
            self.store.save_json(book_id, f"section_packs/{section.section_id}.json", pack)

    @staticmethod
    def _dedupe_by_key(items: list[dict[str, Any]], key: str) -> list[dict[str, Any]]:
        seen: set[str] = set()
        result: list[dict[str, Any]] = []
        for item in items:
            value = str(item.get(key))
            if value and value not in seen:
                seen.add(value)
                result.append(item)
        return result

    def _section_text(self, section: SectionCandidate, page_records: list[dict[str, Any]]) -> str:
        text = "\n\n".join(
            record.get("text", "") for record in page_records[section.page_start - 1 : section.page_end]
        )
        text = normalize_text(text)
        if section.start_heading:
            idx = text.lower().find(section.start_heading.lower())
            if idx >= 0:
                text = text[idx:]
        if section.end_heading:
            idx = text.lower().find(section.end_heading.lower(), max(1, len(section.start_heading or "")))
            if idx > 0:
                text = text[:idx]
        return normalize_text(text)

    @staticmethod
    def _page_context_around(text: str, needle: str, radius: int = 650) -> str:
        normalized = normalize_text(text)
        idx = normalized.upper().find(needle.upper())
        if idx < 0:
            return normalized[:radius].replace("\n", " ")
        start = max(0, idx - radius // 3)
        end = min(len(normalized), idx + radius)
        return normalized[start:end].replace("\n", " ").strip()

    @staticmethod
    def _make_naive_summary(title: str, paragraphs: list[str]) -> str | None:
        if not paragraphs:
            return None
        text = paragraphs[0]
        if text.lower().startswith(title.lower()) and len(paragraphs) > 1:
            text = paragraphs[1]
        text = text.replace("\n", " ")
        return text[:500].strip() + ("..." if len(text) > 500 else "")

    @staticmethod
    def _guess_title(doc: fitz.Document, source: Path) -> str:
        meta_title = (doc.metadata or {}).get("title")
        if meta_title:
            return clean_title(meta_title)
        return source.stem

    @staticmethod
    def _section_sort_key(section_id: str) -> tuple[int, ...]:
        return tuple(int(part) for part in section_id.split(".") if part.isdigit())

    @staticmethod
    def _parent_id(section_id: str) -> str | None:
        parts = section_id.split(".")
        if len(parts) <= 1:
            return None
        return ".".join(parts[:-1])
